# Generated by Django 5.1.3 on 2024-11-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_university'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='established_date',
        ),
        migrations.AddField(
            model_name='university',
            name='established_year',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='university',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
