# Generated by Django 5.1.3 on 2024-12-06 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_university_established_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='student_images/')),
                ('face_encoding', models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
